name: Build Android APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 设置 Java 环境，你的项目明确要求 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      # 2. 设置 Flutter 环境
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      # 3. 构建 APK
      - name: Decode Keystore and Build APK
        run: |
          echo "${{ secrets.BUILD_ANDROID }}" | base64 --decode > android/app/upload-keystore.jks
          flutter build apk --release
        env:
          # 这里的路径对应上面解码生成的文件路径
          KEYSTORE_PATH: "${{ github.workspace }}/android/app/upload-keystore.jks"
          # 这里的 secrets 需要你在 GitHub 仓库 Settings -> Secrets and variables -> Actions 中配置
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 4. 上传构建好的 APK 到 GitHub Actions 结果中
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
